os: linux
services: docker
language: minimal
install: skip
addons:
  apt:
    packages:
    - pass
script: ./travis/run.sh -c
deploy:
  provider: script
  skip_cleanup: true
  script: ./travis/run.sh
  on:
    repo: ghdl/docker
    branch: master
