name: 'daily'

on:
  push:
    paths:
      - 'run.sh'
      - '.github/workflows/daily.yml'
  schedule:
    - cron: '0 0 * * *'

jobs:

  build:
    strategy:
      fail-fast: false
      max-parallel: 3
      matrix:
        backend: [ mcode, llvm-7, gcc-8.3.0 ]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Clone ghdl
      run: git clone https://github.com/ghdl/ghdl
    - name: Build 'ghdl' and 'pkg' images
      run: ./run.sh -b
      env:
        TASK: buster+${{ matrix.backend }}
    - name: Deploy to hub.docker.com
      run: ./run.sh ""
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASS: ${{ secrets.DOCKER_PASS }}
