name: 'ext'

on:
  push:
    paths:
      - 'run.sh'
      - 'cli/*'
      - '.github/workflows/ext.yml'
      - 'ls_debian*.dockerfile'
      - 'gui.dockerfile'
  repository_dispatch:
    types: [ ext ]

env:
  DOCKER_BUILDKIT: 1
  DOCKER_USER: ${{ secrets.DOCKER_USER }}
  DOCKER_PASS: ${{ secrets.DOCKER_PASS }}

jobs:

  ls:
    strategy:
      fail-fast: false
      max-parallel: 2
      matrix:
        task: [ debian, ubuntu ]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build images
      run: ./run.sh -l $TASK
      env:
        TASK: ${{ matrix.task }}
    - name: Deploy to hub.docker.com
      run: ./run.sh ext

  gui:
    needs: [ls]
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build images
      run: ./run.sh -e gui
    - name: Deploy to hub.docker.com
      run: ./run.sh ext
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASS: ${{ secrets.DOCKER_PASS }}
