name: 'ghdl'

on:
  push:
    paths:
      - 'run.sh'
      - '.github/workflows/ghdl.yml'
  schedule:
    - cron: '0 0 * * 5'

jobs:

  build:
    strategy:
      fail-fast: false
      max-parallel: 3
      matrix:
        task: [
          { distro: sid,      backend: mcode ,    args: "--synth" },
          { distro: sid,      backend: mcode,     args: "--gpl" },
          { distro: ubuntu16, backend: mcode ,    args: "--synth" },
          { distro: ubuntu18, backend: mcode ,    args: "--synth" },
          { distro: fedora30, backend: mcode ,    args: "--synth" },
          { distro: fedora31, backend: mcode ,    args: "--synth" },
          #{ distro: buster,   backend: llvm-7,    args: "" },
          { distro: sid,      backend: llvm-8,    args: "--synth" },
          { distro: ubuntu16, backend: llvm-3.9,  args: "--synth" },
          { distro: ubuntu18, backend: llvm-5.0,  args: "--synth" },
          { distro: fedora30, backend: llvm,      args: "--synth" },
          { distro: fedora31, backend: llvm,      args: "--synth" },
          #{ distro: buster,   backend: gcc-8.3.0, args: "" },
          { distro: sid,      backend: gcc-9.1.0, args: "--synth" },
          { distro: fedora30, backend: gcc-8.2.0, args: "--synth" },
          { distro: fedora31, backend: gcc-9.2.0, args: "--synth" },
        ]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Clone ghdl
      run: git clone https://github.com/ghdl/ghdl
    - name: Build 'ghdl' and 'pkg' images
      run: ./run.sh -b $TARGS
      env:
        TASK: ${{ matrix.task.distro }}+${{ matrix.task.backend }}
        TARGS: ${{ matrix.task.args }}
    - name: Deploy to hub.docker.com
      run: ./run.sh ""
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASS: ${{ secrets.DOCKER_PASS }}
