name: 'synth'

on:
  push:
    paths:
      - 'run.sh'
      - 'cli/*'
      - '.github/workflows/synth.yml'
  repository_dispatch:
    types: [ synth ]

env:
  DOCKER_BUILDKIT: 1

jobs:

  synth:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2

    - name: Build images
      run: ./run.sh -e synth

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASS }}

    - name: Deploy to DockerHub
      run: ./run.sh synth
