name: 'test'

on:
  push:
    paths:
      - 'run.sh'
      - '.github/workflows/test.yml'
  schedule:
    - cron: '0 0 * * 5'

jobs:

  build:
    strategy:
      fail-fast: false
      max-parallel: 3
      matrix:
        task: [
          { distro: sid,      backend: mcode ,    args: "" },
          { distro: sid,      backend: mcode,     args: "--gpl --no-synth" },
          { distro: ubuntu18, backend: mcode ,    args: "" },
          { distro: ubuntu20, backend: mcode ,    args: "" },
          { distro: fedora31, backend: mcode ,    args: "" },
          { distro: fedora32, backend: mcode ,    args: "" },
          #{ distro: buster,   backend: llvm-7,    args: "" },
          { distro: sid,      backend: llvm-8,    args: "" },
          { distro: ubuntu18, backend: llvm-5.0,  args: "" },
          { distro: ubuntu20, backend: llvm-10 ,  args: "" },
          { distro: fedora31, backend: llvm,      args: "" },
          { distro: fedora32, backend: llvm,      args: "" },
          #{ distro: buster,   backend: gcc-8.3.0, args: "" },
          { distro: sid,      backend: gcc-9.1.0, args: "" },
          { distro: fedora31, backend: gcc-8.2.0, args: "" },
          { distro: fedora32, backend: gcc-9.2.0, args: "" },
        ]
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2

    - name: Clone ghdl
      run: git clone https://github.com/ghdl/ghdl

    - name: Build 'ghdl' and 'pkg' images
      run: ./run.sh -b $TARGS
      env:
        TASK: ${{ matrix.task.distro }}+${{ matrix.task.backend }}
        TARGS: ${{ matrix.task.args }}

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASS }}

    - name: Deploy to DockerHub
      run: ./run.sh ""
