name: 'vunit'

on:
  push:
    paths:
      - 'run.sh'
      - 'cli/*'
      - '.github/workflows/vunit.yml'
      - 'dockerfiles/vunit'
  repository_dispatch:
    types: [ vunit ]

env:
  DOCKER_BUILDKIT: 1
  DOCKER_USER: ${{ secrets.DOCKER_USER }}
  DOCKER_PASS: ${{ secrets.DOCKER_PASS }}

jobs:

  vunit:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build images
      run: ./run.sh -e vunit
    - name: Deploy to hub.docker.com
      run: ./run.sh vunit
    - run: ./.github/trigger.sh ext
